<?xml version="1.0" encoding="utf-8"?><Database Name="crameasy" Class="OrderPaymentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShortDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Product_ProductVersion" Member="ProductVersions" ThisKey="ProductID" OtherKey="ProductID" Type="ProductVersion" />
    </Type>
  </Table>
  <Table Name="dbo.VersionAttribute" Member="VersionAttributes">
    <Type Name="VersionAttribute">
      <Column Name="VersionAttributeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductVersionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ProductVersion_VersionAttribute" Member="ProductVersion" ThisKey="ProductVersionID" OtherKey="ProductVersionID" Type="ProductVersion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="PaymentID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PaymentStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentCurrency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PaymentException" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CustomerOrder_Payment" Member="CustomerOrder" ThisKey="OrderID" OtherKey="OrderID" Type="CustomerOrder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderItem" Member="OrderItems">
    <Type Name="OrderItem">
      <Column Name="OrderItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProductVersionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ItemDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CustomerOrder_OrderItem" Member="CustomerOrder" ThisKey="OrderID" OtherKey="OrderID" Type="CustomerOrder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductVersion" Member="ProductVersions">
    <Type Name="ProductVersion">
      <Column Name="ProductVersionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShortDescription" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsRecuringPrice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RecurringPaymentTime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityIn" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ProductVersion_VersionAttribute" Member="VersionAttributes" ThisKey="ProductVersionID" OtherKey="ProductVersionID" Type="VersionAttribute" />
      <Association Name="Product_ProductVersion" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerOrder" Member="CustomerOrders">
    <Type Name="CustomerOrder">
      <Column Name="OrderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="IsPaid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExpireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CustomerOrder_Payment" Member="Payments" ThisKey="OrderID" OtherKey="OrderID" Type="Payment" />
      <Association Name="CustomerOrder_OrderItem" Member="OrderItems" ThisKey="OrderID" OtherKey="OrderID" Type="OrderItem" />
    </Type>
  </Table>
</Database>