<?xml version="1.0" encoding="utf-8"?><Database Name="edu" Class="QuestionAnswerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.LoginUser" Member="QALoginUsers">
    <Type Name="QALoginUser">
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="QALoginUser_Answer" Member="Answers" ThisKey="LoginUserID" OtherKey="LoginUserID" Type="Answer" />
      <Association Name="QALoginUser_Question" Member="Questions" ThisKey="LoginUserID" OtherKey="LoginUserID" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.AnswerState" Member="AnswerStates">
    <Type Name="AnswerState">
      <Column Name="AnswerStateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnswerStateText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AnswerState_Answer" Member="Answers" ThisKey="AnswerStateID" OtherKey="AnswerStateID" Type="Answer" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionType" Member="QuestionTypes">
    <Type Name="QuestionType">
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionTypeTnext" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="QuestionType_Question" Member="Questions" ThisKey="QuestionTypeID" OtherKey="QuestionTypeID" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionStatus" Member="QuestionStatus">
    <Type Name="QuestionStatus">
      <Column Name="QuestionStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionStatusText" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Answer" Member="Answers">
    <Type Name="Answer">
      <Column Name="AnswerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AnswerText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="QuestionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AnswerStateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerRate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AnswerState_Answer" Member="AnswerState" ThisKey="AnswerStateID" OtherKey="AnswerStateID" Type="AnswerState" IsForeignKey="true" />
      <Association Name="QALoginUser_Answer" Member="QALoginUser" ThisKey="LoginUserID" OtherKey="LoginUserID" Type="QALoginUser" IsForeignKey="true" />
      <Association Name="Question_Answer" Member="Question" ThisKey="QuestionID" OtherKey="QuestionID" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Questions">
    <Type Name="Question">
      <Column Name="QuestionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditLoginUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InstituteCourceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InstituteSubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tag" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Question_Answer" Member="Answers" ThisKey="QuestionID" OtherKey="QuestionID" Type="Answer" />
      <Association Name="QALoginUser_Question" Member="QALoginUser" ThisKey="LoginUserID" OtherKey="LoginUserID" Type="QALoginUser" IsForeignKey="true" />
      <Association Name="QuestionType_Question" Member="QuestionType" ThisKey="QuestionTypeID" OtherKey="QuestionTypeID" Type="QuestionType" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetAnswerByQuestionID" Method="GetAnswerByQuestionID">
    <Parameter Name="QuestionID" Parameter="questionID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="AnswerStateID" Parameter="answerStateID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAnswerByQuestionIDResult">
      <Column Name="AnswerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AnswerText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="QuestionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AnswerStatus" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="AnswerStateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerRate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PhotoPath" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetQuestionByLoginUserID" Method="GetQuestionByLoginUserID">
    <Parameter Name="LoginUserID" Parameter="loginUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QuestionTypeID" Parameter="questionTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QuestionStatusID" Parameter="questionStatusID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetQuestionByLoginUserIDResult">
      <Column Name="QuestionText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionStatus" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PhotoPath" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="QuestionType" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetQuestionByQuestionID" Method="GetQuestionByQuestionID">
    <Parameter Name="QuestionID" Parameter="questionID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="QuestionTypeID" Parameter="questionTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QuestionStatusID" Parameter="questionStatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="InstituteSubjectID" Parameter="instituteSubjectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="InstituteCourceID" Parameter="instituteCourceID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetQuestionByQuestionIDResult">
      <Column Name="QuestionText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionStatus" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PhotoPath" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="QuestionType" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InstituteCourceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InstituteSubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetQuestionStatus" Method="GetQuestionStatus" IsComposable="true">
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.GetQuestion" Method="GetQuestion">
    <Parameter Name="Keyword" Parameter="keyword" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="QuestionTypeID" Parameter="questionTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QuestionStatusID" Parameter="questionStatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="InstituteCourceID" Parameter="instituteCourceID" Type="System.Int32" DbType="Int" />
    <Parameter Name="InstituteSubjectID" Parameter="instituteSubjectID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetQuestionResult">
      <Column Name="QuestionText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LoginUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionStatus" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PhotoPath" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="QuestionType" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="QuestionStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>