delete from dbo.Answer
delete from dbo.AnswerState
delete from dbo.Article
delete from dbo.College
delete from dbo.Comment
delete from dbo.InstituteCourceUser
delete from dbo.InstituteSubject
delete from dbo.InstituteCource
delete from dbo.Cource
delete from dbo.CourceCatagory
delete from dbo.DocumentCource
delete from dbo.Document
delete from dbo.Event
delete from dbo.UserExam
delete from dbo.EXM_UserAnswer
delete from dbo.EXM_Answer
delete from dbo.EXM_Question
delete from dbo.Exam
delete from dbo.HomeWork
delete from portalsetting
delete from dbo.Institute
delete from dbo.InstituteCource
delete from dbo.InstituteUser
delete from dbo.InstituteUserInUserType
delete from dbo.InstituteUserType
delete from dbo.InstituteUserTypeAccess
delete from dbo.ShareGroup

delete from dbo.Message
delete from dbo.Question
delete from dbo.QuestionStatus
delete from dbo.QuestionType
delete from dbo.Share
delete from dbo.ShareUser
delete from dbo.Tutorial
delete from dbo.TutorialType
delete from dbo.UserEducation
delete from ContentHistory
delete from dbo.LoginUser
delete from dbo.aspnet_Membership
delete from dbo.aspnet_Users