delete from dbo.CourceCatagory
delete from dbo.Cource
delete from dbo.InstituteCource
delete from dbo.College
delete from dbo.Cource
delete from dbo.CourceCatagory
delete from dbo.Exam
delete from dbo.EXM_Answer
delete from dbo.EXM_Question
delete from dbo.EXM_UserAnswer
delete from dbo.Institute
delete from dbo.InstituteCource
delete from dbo.InstituteUser
delete from dbo.InstituteUserType
delete from dbo.Instructor
delete from dbo.QuestionStatus
delete from dbo.QuestionType
delete from dbo.Tutorial
delete from dbo.TutorialType
delete from dbo.UserEducation
delete from dbo.UserExam

delete from dbo.Question
delete from dbo.Answer
delete from dbo.AnswerState
delete from dbo.Message
delete from dbo.Tutorial
delete from dbo.UserEducation
delete from dbo.LoginUser
delete from dbo.aspnet_Users
delete from dbo.aspnet_Membership